/**
 * Trigger, Regex Rule, and Variable type definitions
 * Phase 4: extends the Phase 2 basic regex system with DB-backed rules,
 * a variable store, and a trigger engine.
 */

// ─── Regex Rules (DB-backed, extends Phase 2 inline rules) ────────────────

export type RegexPlacement =
  | 'user_input'
  | 'ai_output'
  | 'display_only'
  | 'system_prompt';

export type RegexRuleScope = 'global' | 'character';

export interface DbRegexRule {
  id: string;
  name: string;
  enabled: boolean;
  scope: RegexRuleScope;
  characterId: string | null;
  findRegex: string;
  replaceString: string;
  placement: RegexPlacement[];
  flags: string;
  order: number;
  createdAt: string;
  updatedAt: string;
}

export interface CreateDbRegexRulePayload {
  name: string;
  enabled?: boolean;
  scope?: RegexRuleScope;
  characterId?: string | null;
  findRegex: string;
  replaceString?: string;
  placement?: RegexPlacement[];
  flags?: string;
  order?: number;
}

export interface UpdateDbRegexRulePayload extends Partial<CreateDbRegexRulePayload> {}

// ─── Variables ─────────────────────────────────────────────────────────────

export type VariableScope = 'global' | 'chat';

export interface Variable {
  id: string;
  scope: VariableScope;
  chatId: string | null;
  key: string;
  value: string;
  createdAt: string;
  updatedAt: string;
}

// ─── Triggers ──────────────────────────────────────────────────────────────

export type TriggerActivation =
  | 'before_generation'
  | 'after_generation'
  | 'on_user_input'
  | 'on_display'
  | 'manual';

export type TriggerScope = 'global' | 'character';

export interface TriggerCondition {
  type: 'variable' | 'message_count' | 'text_match' | 'regex_match';
  field: string;
  operator: '==' | '!=' | '>' | '<' | '>=' | '<=' | 'contains' | 'matches';
  value: string | number;
  logicOp?: 'AND' | 'OR';
}

export type TriggerEffect =
  | { type: 'set_variable'; key: string; value: string; scope: VariableScope; operator: '=' | '+=' | '-='; }
  | { type: 'inject_prompt'; content: string; position: 'before_system' | 'after_system' | 'before_history' | 'after_history'; }
  | { type: 'modify_message'; target: 'last' | number; find: string; replace: string; }
  | { type: 'run_regex'; ruleId: string; }
  | { type: 'show_alert'; message: string; style: 'info' | 'warning'; }
  | { type: 'stop_generation'; }
  | { type: 'run_trigger'; triggerId: string; };

export interface Trigger {
  id: string;
  name: string;
  enabled: boolean;
  scope: TriggerScope;
  characterId: string | null;
  activation: TriggerActivation;
  conditions: TriggerCondition[];
  effects: TriggerEffect[];
  order: number;
  createdAt: string;
  updatedAt: string;
}

export interface CreateTriggerPayload {
  name: string;
  enabled?: boolean;
  scope?: TriggerScope;
  characterId?: string | null;
  activation?: TriggerActivation;
  conditions?: TriggerCondition[];
  effects?: TriggerEffect[];
  order?: number;
}

export interface UpdateTriggerPayload extends Partial<CreateTriggerPayload> {}

// ─── Trigger execution context ────────────────────────────────────────────

export interface TriggerExecutionContext {
  /** Current message content (user input or AI output) */
  messageContent: string;
  /** Chat ID for scoped variables */
  chatId?: string;
  /** Character ID for scoped triggers */
  characterId?: string;
  /** Total message count in the chat */
  messageCount: number;
  /** Injections accumulated by trigger effects */
  injections: Array<{ content: string; position: string }>;
  /** Alerts generated by trigger effects */
  alerts: Array<{ message: string; style: string }>;
  /** Whether generation should be stopped */
  stopGeneration: boolean;
}
